# Generated by Django 2.1.4 on 2019-01-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theory',
            options={'verbose_name_plural': 'Theories'},
        ),
        migrations.AlterField(
            model_name='theory',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
