# Generated by Django 2.1.4 on 2019-01-11 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190103_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='locations/%Y/%m/%d')),
                ('sub_image_1', models.ImageField(blank=True, upload_to='locations/%Y/%m/%d')),
                ('sub_image_2', models.ImageField(blank=True, upload_to='locations/%Y/%m/%d')),
                ('sub_image_3', models.ImageField(blank=True, upload_to='locations/%Y/%m/%d')),
                ('youtube_link', models.CharField(blank=True, max_length=250)),
                ('wiki_link', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile')),
            ],
        ),
    ]
