# Generated by Django 2.1.4 on 2019-01-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='main_image',
            field=models.ImageField(default='/static/img/abandoned-ancient-antique-672630.jpg', upload_to='locations/%Y/%m/%d'),
        ),
    ]
