# Generated by Django 2.1.4 on 2019-01-22 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20190117_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 22, 15, 46, 0, 276763)),
        ),
    ]
