# Generated by Django 2.1.4 on 2019-01-22 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 15, 47, 13, 143389)),
        ),
    ]
